#!/usr/bin/env python3

import os, glob

# Adding the sample configuration sets (generated by FeatureIDE) to an array
sample_configurations = []

# for variant in glob.glob("measures/products/*.config"):
for variant in glob.glob("/home/xternava/Documents/GitHub/bloat-energy-consumption/src/ct-configurations/*.xml"):
    lineList = list()
    with open(variant) as f:
        for line in f:
            lineList = [line.rstrip('\n') for line in open(variant)]
        sample_configurations.append(lineList)


# All single and sample configurations, 
# which will be used to measure the changes on
# the binary size and number of gadgets in x264
all_options =  [*sample_configurations]

# print samle of configurations

if __name__ == "__main__":
    print(all_options)