FROM ubuntu:22.04

# Avoid interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
    apt-get -y install clang-12
# Create a working directory
WORKDIR /workspace

# Install Jupyter
RUN pip3 install --upgrade pip && \
    pip3 install notebook

# Expose Jupyter port
EXPOSE 8888

# Command to run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
